services:
  minio:
    image: minio/minio
    ports:
      - 7900:9000
      - 7901:9001
    environment:
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      apk add nc &&
      while ! nc -z minio 9000; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5 &&
      /usr/bin/mc config host add tmc http://minio:9000 access-key secret-key;
      /usr/bin/mc mb tmc/app;
      /usr/bin/mc policy download tmc/app;
      exit 0;"
